import type { LucideIcon } from 'lucide-react';
import {
  ArrowLeft,
  Bell,
  Bot,
  Brain,
  CheckCircle2,
  ChevronDown,
  CircleAlert,
  ClipboardCopy,
  Command,
  Database,
  Download,
  Eye,
  EyeOff,
  FileText,
  Files,
  Folder,
  Globe,
  Handshake,
  Hash,
  Info,
  Library,
  LoaderCircle,
  LogOut,
  Menu,
  Monitor,
  Moon,
  MoreHorizontal,
  Navigation,
  Paperclip,
  Pin,
  Plus,
  RefreshCcw,
  Send,
  Square,
  Sun,
  TriangleAlert,
  Upload,
  UserPlus,
  Wrench,
  X,
} from 'lucide-react';

export const iconRegistry = {
  'arrow-left': ArrowLeft,
  bell: Bell,
  bot: Bot,
  brain: Brain,
  check: CheckCircle2,
  'chevron-down': ChevronDown,
  alert: CircleAlert,
  copy: ClipboardCopy,
  command: Command,
  database: Database,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  files: Files,
  folder: Folder,
  globe: Globe,
  handshake: Handshake,
  hash: Hash,
  info: Info,
  library: Library,
  loader: LoaderCircle,
  logout: LogOut,
  menu: Menu,
  monitor: Monitor,
  moon: Moon,
  more: MoreHorizontal,
  navigation: Navigation,
  paperclip: Paperclip,
  pin: Pin,
  plus: Plus,
  retry: RefreshCcw,
  send: Send,
  stop: Square,
  sun: Sun,
  warning: TriangleAlert,
  upload: Upload,
  'user-plus': UserPlus,
  wrench: Wrench,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
